### ISSUE TITLE
For One question

### ISSUE THREAD

**Issue by xzcb2008** [cooltey/C.P.Sub#1]
Hi,
Thanks for u create a super useful system.
Here is my question show below

Everything work fine in English...
But when I use Chinese As post title, the system will not record anything...
So I can just use English only

簡單的說
我只要在標題或是作者欄位輸入中文
所有的中文在布告欄中都會消失
但是用英文的標題就不會
目前使用的是免費空間

謝謝拉，這系統太棒了
想請您幫忙一下
不知道哪裡有問題了

**Comment by cooltey** [comment]
@xzcb2008 感謝您喜歡我的系統！

想請問一下，你是用什麼版本的 PHP 呢？很有可能就是因為 PHP 版本低於 5.3 才會造成這個問題

**Comment by xzcb2008** [comment]
謝謝您的回應，問題的確出在我沒看清楚
我目前5.2升到5.3後完美運行中
謝謝您的幫忙，以及回應

Thanks for ur help
I upgrade the php system to 5.3
Now everything work fine.

best regards,

**Comment by cooltey** [comment]
了解，感謝囉
