### ISSUE TITLE
在PHP7使用會出現問題

### ISSUE THREAD

**Issue by jimmychn** [cooltey/C.P.Sub#5]
Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; Settings has a deprecated constructor in \CPSub\class\settings.php on line 8

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; Lib has a deprecated constructor in \WEB\CPSub\class\lib.php on line 8

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; Article has a deprecated constructor in \WEB\CPSub\class\article.php on line 8

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; Pager has a deprecated constructor in \WEB\CPSub\class\page.php on line 10

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; Template has a deprecated constructor in \WEB\CPSub\class\template.php on line 8

**Comment by cooltey** [comment]
已修復，請下載 v5.35 版本，謝謝您。
